Feature/shop 589
foodist/messaging-bundle pull request #1
Opened 2021-12-16 08:20 UTC by MNawatzkiIqanta

2021-12-21 19:38 UTC, m4rcw0lf-Foodist commented
Bitte Merge Konflikt lösen.

2021-12-21 19:39 UTC, m4rcw0lf-Foodist requested changes

2021-12-21 19:39 UTC, m4rcw0lf-Foodist commented on src/Message/Customer/CustomerCreatedMessage.php
>      public function __construct(protected string $customerId, protected ?\DateTime $createdAt = null, protected array $metaData = [])
Dann kann customerId aus der Signatur raus!?

2021-12-22 15:27 UTC, closed without merging

2021-12-22 15:28 UTC, MNawatzkiIqanta commented
Closed because changes made by Alex fixed the issue.